---
title: "update method of lme4 R package"
author: "Andrey Ziyatdinov"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: united
    toc: true
    keep_md: true
---


## Include

```{r inc}
library(lme4)
library(solaris)
```

```{r}
library(microbenchmark)
library(plyr)
library(ggplot2)
```

## Benchmarking of update methods

```{r m1, cache = TRUE}
f1 <- Reaction ~ Days + (1 | Subject)
m1 <- lmer(f1, sleepstudy)
start.m1 <- list(theta = getME(m1, "theta"))
start2.m1 <- getME(m1, c("theta", "fixef"))
m2 <- update(m1, Reaction ~ Days + (1|Subject))
m3 <- update(m1, Reaction ~ (1|Subject))
```

```{r bench1, cache = TRUE}
tab <- microbenchmark(
  m1 = lmer(f1, sleepstudy),
  m1.opt.none = lmer(f1, sleepstudy, control = lmerControl(optimizer = "none")),
  m1.update = update(m1, f1, sleepstudy),
  m1.start = update(m1, f1, start = start.m1),
  m1.start2 = update(m1, f1, start = start2.m1),
  m1.start.opt.none = lmer(f1, sleepstudy, control = lmerControl(optimizer = "none"), start = start.m1),
  #m2 = lmer(Reaction ~ Days + (1 | Subject), sleepstudy),
  #m3 = lmer(Reaction ~ (1 | Subject), sleepstudy),  
  #m2.update = update(m1, Reaction ~ Days + (1|Subject)),
  #m3.update = update(m1, Reaction ~ (1|Subject)),
  times = 10)
```

```{r print_tab}
tab
```

```{r plot_tab}
autoplot(tab)
```

## Check model equvalence


### Atemp 1: main function

```{r mod_eq, cache = TRUE}
f1 <- Reaction ~ Days + (1 | Subject)

mod1 <- lmer(f1, sleepstudy)

start.mod1 <- list(theta = getME(mod1, "theta"))
mod2 <- lmer(f1, sleepstudy, control = lmerControl(optimizer = "none"), start = start.mod1)
#mod2 <- update(mod1, f1, start = start.mod1)

mod3 <- lmer(f1, sleepstudy, control = lmerControl(optimizer = "none"))

# check
fixef(mod1)
fixef(mod2)
getME(mod1, "theta")
getME(mod2, "theta")
```

### Atemp 2: modular call


```{r mod_eq_2}
lmod <- lFormula(f1, sleepstudy)
devfun <- do.call(mkLmerDevfun, lmod)
opt <- optimizeLmer(devfun)
mod1 <- mkMerMod(environment(devfun), opt, lmod$reTrms, fr = lmod$fr)

start.mod1 <- list(theta = getME(mod1, "theta"))

opt2 <- list(par = as.numeric(start.mod1$theta), fval = NA,conv = 1000, message="start copied")
mod2 <- mkMerMod(environment(devfun), opt2, lmod$reTrms, fr = lmod$fr)

# check
fixef(mod1)
fixef(mod2)
getME(mod1, "theta")
getME(mod2, "theta")
```

## `relmatLmer` function

### Benchmarking 2

```{r bench2, cache = TRUE}
f1 <- Reaction ~ Days + (1 | Subject)
m1 <- lmer(f1, sleepstudy)
m2 <- relmatLmer(f1, sleepstudy)

tab2 <- microbenchmark(
  m1 = lmer(f1, sleepstudy),
  m1.opt.none = lmer(f1, sleepstudy, control = lmerControl(optimizer = "none")),
  m1.start = update(m1, f1, start = start.m1),
  m2 = relmatLmer(f1, sleepstudy),
  m2.update = update(m2, f1),
  m2.start = relmatLmer(f1, sleepstudy, start = start.m1),
  m2.update.start = update(m2, f1, start = start.m1),
  m2.opt.none.start = relmatLmer(f1, sleepstudy, control = lmerControl(optimizer = "none"), start = start.m1),
  m2.update.opt.none.start = update(m2, f1, control = lmerControl(optimizer = "none"), start = start.m1),
  times = 10)
```

```{r plot_tab2}
autoplot(tab2)
```

### Model comparison

```{r mod_comp_2, cache = TRUE}
system.time(mod1 <- lmer(f1, sleepstudy))
system.time(mod2 <- relmatLmer(f1, sleepstudy, control = lmerControl(optimizer = "none"), start = start.m1))
system.time(mod3 <- update(mod1, f1, control = lmerControl(optimizer = "none"), start = start.m1))

# check
fixef(mod1)
fixef(mod2)
fixef(mod3)
getME(mod1, "theta")
getME(mod2, "theta")
getME(mod3, "theta")
```
